### ISSUE TITLE
SCRUM Ceremonias - Sprint Retrospective Meeting

### ISSUE THREAD

**Issue by RochettiUriel** [RochettiUriel/ISPC-Aula-25-Grupo-2#15]
#### Desarrollar el concepto de:

"Sprint Retrospective Meeting"

Guardar los cambios en el archivo Readme.md

**Comment by EldaRodriguez22** [comment]
Sprint Restrospective Meeting (Reunión de retrospectiva de  del Sprint). Se produce también al finalizar el Sprint y tiene por objeto documentar que ha funcionado en la Sprint. La idea es centrar al equipo en lo que salió bien y en lo que se debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.
