### ISSUE TITLE
SCRUM Roles - Scrum Master

### ISSUE THREAD

**Issue by RochettiUriel** [RochettiUriel/ISPC-Aula-25-Grupo-2#7]
#### Desarrollar el concepto de:

-  "Scrum Master" 

Guardar los cambios en el archivo Readme.md

**Comment by JVLezcano** [comment]
Es la figura que lidera los equipos en la gestión ágil de proyectos. Su misión es que los equipos de trabajo alcancen sus objetivos hasta llegar a la fase de *sprint final*, eliminando cualquier dificultad o problema en el camino. Trabaja con el *Product Owner, Stakeholders y otras figuras* definiendo los objetivos del proyecto, detectando riesgos durante el sprint y buscando actualizaciones para las tareas a desarrollar; representa al equipo en las reuniones, presenta los temas de diseño técnico y las acciones del equipo realizadas; asesora y refuerza al equipo para que trabajen auto-organizadamente, motivados y concientizados según los objetivos, se encarga de que las reglas y procedimientos se cumplan, es el guía y moderador del equipo.
